ALTER TABLE users
ADD COLUMN IF NOT EXISTS puzzle_rating_rd DOUBLE PRECISION NOT NULL DEFAULT 350.0;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS puzzle_rating_volatility DOUBLE PRECISION NOT NULL DEFAULT 0.06;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS puzzle_rating_updated_at TIMESTAMP NOT NULL DEFAULT NOW();
