import type { LevelData } from "./types"

export const NEON_LEVELS: LevelData[] = [
  {
    id: 1,
    name: "NEON GRID",
    gateSpacingPx: 580,
    gateCount: 4,
    bossName: "ROOK GOLEM",
    bossMaxHP: 3,
    puzzles: [
      {
        type: "G",
        label: "GATE 1",
        tactic: "PAWN ADVANCE",
        task: "White to move. Push the pawn to promote it to a queen!",
        fuelGain: 0.28,
        board: [[null, null, null, "bk", null, null, null, null], [null, null, null, null, null, null, "wp", null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, "wk", null, null, null, null]],
        sol: { fr: [1, 6], to: [0, 6] },
        hint: [1, 6],
        explain: "Pawn promotes to queen.",
      },
      {
        type: "G",
        label: "GATE 2",
        tactic: "FREE CAPTURE",
        task: "White queen: take the undefended rook for free.",
        fuelGain: 0.28,
        board: [[null, null, null, "bk", null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, "br", null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, "wq", null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, "wk", null, null, null, null]],
        sol: { fr: [4, 4], to: [2, 5] },
        hint: [4, 4],
        explain: "Queen takes rook for free.",
      },
      {
        type: "G",
        label: "GATE 3",
        tactic: "KNIGHT FORK",
        task: "White knight forks king and queen.",
        fuelGain: 0.28,
        board: [[null, null, null, null, "bk", null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, "bq", null, null, null, null, null, null], [null, null, null, "wn", null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, "wk", null, null, null, null]],
        sol: { fr: [4, 3], to: [2, 4] },
        hint: [4, 3],
        explain: "Knight to e6 forks king and queen.",
      },
      {
        type: "G",
        label: "GATE 4",
        tactic: "BACK RANK MATE",
        task: "White rook delivers back rank mate.",
        fuelGain: 0.28,
        board: [["bk", null, null, null, null, null, null, null], ["bp", "bp", null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], ["wr", null, null, null, "wk", null, null, null]],
        sol: { fr: [7, 0], to: [0, 0] },
        hint: [7, 0],
        explain: "Rook to a8 checkmate.",
      },
      {
        type: "B",
        label: "BOSS HIT",
        tactic: "MATE IN ONE",
        task: "Deliver checkmate in one move.",
        fuelGain: 0,
        board: [["br", null, "bb", "bq", "bk", "bb", null, "br"], ["bp", "bp", "bp", "bp", null, "bp", null, "bp"], [null, null, null, null, null, null, null, null], [null, null, null, null, "bp", null, "bp", null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, "wn", null, null], ["wp", "wp", "wp", "wp", "wp", "wp", null, "wp"], ["wr", "wn", "wb", "wq", "wk", "wb", null, "wr"]],
        sol: { fr: [7, 3], to: [3, 7] },
        hint: [7, 3],
        explain: "Queen to h5 checkmate.",
      },
    ],
  },
  {
    id: 2,
    name: "CYBER DEPTHS",
    gateSpacingPx: 580,
    gateCount: 4,
    bossName: "SHADOW KNIGHT",
    bossMaxHP: 3,
    puzzles: [
      {
        type: "G",
        label: "GATE 1",
        tactic: "DISCOVERED CHECK",
        task: "Move bishop to reveal rook check.",
        fuelGain: 0.28,
        board: [[null, null, null, null, "bk", null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, "wb", null, null, null, null], ["wr", null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, "wk", null, null, null]],
        sol: { fr: [3, 3], to: [1, 5] },
        hint: [3, 3],
        explain: "Discovered check.",
      },
      {
        type: "G",
        label: "GATE 2",
        tactic: "ABSOLUTE PIN",
        task: "Pin bishop to king with rook.",
        fuelGain: 0.28,
        board: [[null, null, null, null, "bk", null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, "bb", null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], ["wr", null, null, null, null, null, null, null], [null, null, null, null, "wk", null, null, null]],
        sol: { fr: [6, 0], to: [0, 0] },
        hint: [6, 0],
        explain: "Absolute pin created.",
      },
      {
        type: "G",
        label: "GATE 3",
        tactic: "SKEWER",
        task: "Skewer king and queen with rook.",
        fuelGain: 0.28,
        board: [[null, null, null, null, null, null, null, "bk"], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, "bq", null], [null, null, null, null, null, null, null, null], ["wr", null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, "wk", null, null, null]],
        sol: { fr: [4, 0], to: [0, 0] },
        hint: [4, 0],
        explain: "Skewer landed.",
      },
      {
        type: "G",
        label: "GATE 4",
        tactic: "KNIGHT FORK",
        task: "Knight forks king and rook.",
        fuelGain: 0.28,
        board: [[null, null, null, null, null, null, null, "bk"], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, "br", null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, "wn", null, null, null, null, null, null], [null, null, null, null, "wk", null, null, null]],
        sol: { fr: [6, 1], to: [4, 0] },
        hint: [6, 1],
        explain: "Knight fork wins material.",
      },
      {
        type: "B",
        label: "BOSS HIT",
        tactic: "KNIGHT FORK ATTACK",
        task: "Fork king and queen with knight.",
        fuelGain: 0,
        board: [[null, null, null, null, "bk", null, null, null], [null, null, null, null, "bp", null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, "bq", null, null, null, null], [null, null, null, null, null, null, null, null], [null, "wn", null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, "wk", null, null, null]],
        sol: { fr: [5, 1], to: [3, 2] },
        hint: [5, 1],
        explain: "Knight fork found.",
      },
    ],
  },
  {
    id: 3,
    name: "VOID CORE",
    gateSpacingPx: 580,
    gateCount: 4,
    bossName: "QUANTUM QUEEN",
    bossMaxHP: 4,
    puzzles: [
      {
        type: "G",
        label: "GATE 1",
        tactic: "DOUBLE CHECK",
        task: "Move knight for double check.",
        fuelGain: 0.28,
        board: [[null, null, null, null, "bk", null, null, null], [null, null, null, null, "bp", "bp", "bp", null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, "wb", null, null, null, null], [null, null, "wn", null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, "wk", null, null, null]],
        sol: { fr: [5, 2], to: [3, 4] },
        hint: [5, 2],
        explain: "Double check!",
      },
      {
        type: "G",
        label: "GATE 2",
        tactic: "ZUGZWANG",
        task: "Move king to force zugzwang.",
        fuelGain: 0.28,
        board: [[null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, "wk", null, null], [null, null, null, null, null, null, null, null], [null, null, null, "bk", null, "wp", null, null]],
        sol: { fr: [5, 5], to: [6, 5] },
        hint: [5, 5],
        explain: "Zugzwang setup complete.",
      },
      {
        type: "G",
        label: "GATE 3",
        tactic: "PROMOTION MATE",
        task: "Promote pawn for mate.",
        fuelGain: 0.28,
        board: [[null, null, null, null, "bk", null, null, null], [null, null, null, null, null, null, "wp", null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null], [null, null, null, null, "wk", null, null, null]],
        sol: { fr: [1, 6], to: [0, 6] },
        hint: [1, 6],
        explain: "Promotion mate executed.",
      },
      {
        type: "G",
        label: "GATE 4",
        tactic: "QUEEN SACRIFICE",
        task: "Find the queen sacrifice move.",
        fuelGain: 0.28,
        board: [[null, null, null, null, "bk", null, null, null], [null, null, null, null, "bp", "bp", null, "bp"], [null, null, null, null, null, null, "bp", null], [null, null, null, null, null, null, "wq", null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, "wk"], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null]],
        sol: { fr: [3, 6], to: [1, 6] },
        hint: [3, 6],
        explain: "Queen sacrifice found.",
      },
      {
        type: "B",
        label: "FINAL HIT",
        tactic: "MATING NET",
        task: "Deliver final checkmate.",
        fuelGain: 0,
        board: [[null, null, null, null, "bk", null, null, null], [null, null, null, null, "bp", "bp", null, "bp"], [null, null, null, null, null, null, "bp", null], [null, null, null, null, null, null, "wq", null], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, "wk"], [null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null]],
        sol: { fr: [3, 6], to: [1, 6] },
        hint: [3, 6],
        explain: "Final mating net complete.",
      },
    ],
  },
]
